/**
 * constants.ts — RailNexus Backend
 * Global enumeration and domain constants.
 */

export enum Role {
  MAINTENANCE_ENGINEERING = 'MAINTENANCE_ENGINEERING',
  MAINTENANCE_SNT = 'MAINTENANCE_SNT',
  MAINTENANCE_OHE = 'MAINTENANCE_OHE',
  CONTROLLER = 'CONTROLLER',
  ADMIN = 'ADMIN',
}

export enum Department {
  ENGINEERING = 'ENGINEERING',
  SNT = 'SNT',
  OHE = 'OHE',
  CONTROLLER = 'CONTROLLER',
}

export enum RequestPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  ANALYZING = 'ANALYZING',
  RECOMMENDED = 'RECOMMENDED',
  APPROVED = 'APPROVED',
  MODIFIED = 'MODIFIED',
  REJECTED = 'REJECTED',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum BrainPlanningRequestStatus {
  PENDING = 'PENDING',
  RECOMMENDED = 'RECOMMENDED',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ControllerAction {
  APPROVE = 'APPROVE',
  MODIFY = 'MODIFY',
  REJECT = 'REJECT',
}

export enum PlanningMode {
  INITIAL = 'INITIAL',
  REPLAN = 'REPLAN',
}

export enum AuditAction {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_ANALYSIS_STARTED = 'REQUEST_ANALYSIS_STARTED',
  BRAIN_ANALYSIS_COMPLETED = 'BRAIN_ANALYSIS_COMPLETED',
  REQUEST_RECOMMENDED = 'REQUEST_RECOMMENDED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_MODIFIED = 'REQUEST_MODIFIED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  PLAN_REANALYZED = 'PLAN_REANALYZED',
  REQUEST_CANCELLED = 'REQUEST_CANCELLED',
  REQUEST_SCHEDULED = 'REQUEST_SCHEDULED',
}

export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_ROLE = 'INVALID_ROLE',
  INVALID_DEPARTMENT = 'INVALID_DEPARTMENT',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  CONTROLLER_ID_EXISTS = 'CONTROLLER_ID_EXISTS',
  IMMUTABLE_FIELD = 'IMMUTABLE_FIELD',
  IDEMPOTENCY_KEY_OWNERSHIP_VIOLATION = 'IDEMPOTENCY_KEY_OWNERSHIP_VIOLATION',
  REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
  BRAIN_UNAVAILABLE = 'BRAIN_UNAVAILABLE',
  BRAIN_TIMEOUT = 'BRAIN_TIMEOUT',
  BRAIN_INVALID_RESPONSE = 'BRAIN_INVALID_RESPONSE',
  INVALID_BRAIN_RESPONSE = 'INVALID_BRAIN_RESPONSE',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  INVALID_CONTROLLER_ACTION = 'INVALID_CONTROLLER_ACTION',
  REQUEST_ALREADY_DECIDED = 'REQUEST_ALREADY_DECIDED',
  STALE_PLAN = 'STALE_PLAN',
  PLANNING_STATE_CONFLICT = 'PLANNING_STATE_CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

